Bdi 39 loginform
BDI-HU/WeatherProject pull request #23
Opened 2023-04-18 11:17 UTC by timrebergen

Working changes to the token storage

2023-04-18 11:43 UTC, jafetsinke requested changes

2023-04-18 11:43 UTC, jafetsinke commented on bdi-frontend/src/views/RegisterComponent.vue
> +      <v-card-title class="" style="color: #4FC6EC; font-weight: 700; font-size: 36px" align="center">
Shouldn't use inline styles in favour of vuetify classes

2023-04-18 11:43 UTC, jafetsinke commented on bdi-frontend/src/views/RegisterComponent.vue
> +      show1: true,
Show/hide button does not work, also getting `[Vue warn]: Property "show1" was accessed during render but is not defined on instance. `

2023-04-18 11:43 UTC, jafetsinke commented on .idea/WeatherProject.iml
Probably want to add .idea to gitignore

2023-04-18 11:43 UTC, jafetsinke commented on bdi-frontend/src/App.vue
> +<script>
not sure why this change was made? belongs to commit "almost_functional_login"

2023-04-18 11:43 UTC, jafetsinke commented on bdi-frontend/src/appRouter.js
Aren't we using 2 routers at the same time this way? router/index.ts and appRouter.js

2023-04-18 11:43 UTC, jafetsinke commented on bdi-frontend/src/store/auth.js
Request is working!

2023-04-18 11:43 UTC, jafetsinke commented on bdi-frontend/src/views/RegisterComponent.vue
> -      show2: false,
password is shown by default

2023-04-18 11:43 UTC, jafetsinke commented on bdi-frontend/src/views/LoginComponent.vue
> +          @click:append="show1 = !show1"
Show/hide is not working. suggest rename variable name aswell

2023-04-18 11:43 UTC, jafetsinke commented on bdi-frontend/src/views/LoginComponent.vue
> +          color="#4FC6EC"
color can take "primary" instead of HEX

2023-04-18 11:43 UTC, jafetsinke commented on bdi-frontend/src/views/LoginComponent.vue
> +          style="color: white; font-weight: 700"
Prevent using inline styles

2023-04-19 09:15 UTC, timrebergen commented
Fixed the stuffies

2023-04-19 09:23 UTC, jafetsinke requested changes

2023-04-19 09:23 UTC, jafetsinke commented on bdi-frontend/.gitignore
nice

2023-04-19 09:23 UTC, jafetsinke commented on bdi-frontend/src/views/RegisterComponent.vue
> +      show1: true,
Vue warn is fixed! show/hide button not working

2023-04-19 09:37 UTC, jafetsinke approved these changes

2023-04-19 09:37 UTC, merged