Bdi 39 loginform
BDI-HU/WeatherProject pull request #42
Opened 2023-06-13 09:13 UTC by timrebergen

2023-06-14 13:07 UTC, jafetsinke requested changes

2023-06-14 13:07 UTC, jafetsinke commented on bdi-frontend/src/views/LoginComponent.vue
> +    <v-card class="card mx-auto px-6 py-8">
Nice use of vuetify styling and clear comments

2023-06-14 13:07 UTC, jafetsinke commented on bdi-frontend/src/views/LoginComponent.vue
> +          const pattern = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
email validation works as expected.

2023-06-15 09:20 UTC, timrebergen commented on bdi-frontend/src/App.vue
> +      getUserProfile: "getUserProfile",
Forgot to remove. Fixed now :)

2023-06-15 11:36 UTC, jafetsinke requested changes

2023-06-15 11:36 UTC, jafetsinke commented on bdi-frontend/src/appRouter.js
> -  { path: "/login", component: Login },
I suggest changing the naming

2023-06-15 11:36 UTC, jafetsinke commented on bdi-frontend/src/store/auth.js
> +      commit("setRegisterApiStatus", 200);
You should probably check if the status code is 200

2023-06-15 11:36 UTC, jafetsinke commented on bdi-frontend/src/views/RegisterComponent.vue
>  <style scoped>
remove empty style tag

2023-06-15 11:36 UTC, jafetsinke commented on bdi-frontend/src/views/RegisterComponent.vue
> +        this.snackbar = {
Maybe refactor error handling to prevent duplicate code between login and register?

2023-06-16 10:29 UTC, timrebergen commented on bdi-frontend/src/views/RegisterComponent.vue
>  <style scoped>
Fixed

2023-06-16 10:33 UTC, timrebergen commented on bdi-frontend/src/views/RegisterComponent.vue
> +        this.snackbar = {
This is possible but requires further work. If it is okay for now, I would like to keep the error handling as it is for now, since the current error handling does follow best practice standards from the Axios documentation (besides that, it also does actually work).

2023-06-16 10:34 UTC, timrebergen commented on bdi-frontend/src/appRouter.js
> +  { path: "/loginView", component: LoginComponent },
Changed path name to "loginView

2023-06-16 10:35 UTC, timrebergen commented on bdi-frontend/src/store/auth.js
> +      console.log(response)
Removed in new commit. My mistake

2023-06-16 10:35 UTC, timrebergen commented on bdi-frontend/src/styles/RegisterLogin.css
>  }
Corrected name of font family

2023-06-16 10:36 UTC, timrebergen commented on bdi-frontend/src/views/LoginComponent.vue
> +          <router-link to="/register" class=" route text-primary font-weight-bold">Maak account aan
Implemented route class name

2023-06-16 10:36 UTC, timrebergen commented on bdi-frontend/src/views/LoginComponent.vue
> +.route {
This is code to remove the underline from router links. Per request of Wim

2023-06-16 10:36 UTC, timrebergen commented on bdi-frontend/src/views/RegisterComponent.vue
> +        <v-alert v-if="errorMessage" color="error" class="errorPassword justify-center">{{ errorMessage }}</v-alert>
Changed html <p> tag to Vuetify specific alert component. This to follow quality criteria guidelines

2023-06-16 10:37 UTC, timrebergen commented on bdi-frontend/src/views/RegisterComponent.vue
> +            :disabled="!userCredentials.email || !userCredentials.password || !userCredentials.name || this.userCredentials.password !== this.confirm || this.userCredentials.password.length < 8"
Button is now disabled if the password character length is less than 8

2023-06-16 10:37 UTC, timrebergen commented on bdi-frontend/src/views/RegisterComponent.vue
> +  color: inherit
Same with the previous router link styling

2023-06-16 10:51 UTC, jafetsinke commented on bdi-frontend/src/appRouter.js
> +  { path: "/loginView", component: LoginComponent },
path shouldn't be changed as /login is perfectly fine. However the component name should be

2023-06-16 10:53 UTC, jafetsinke requested changes
Lot of improvements, code looks better and cleaner. Only a few small things requestes

2023-06-16 13:23 UTC, jafetsinke commented
Looks good!

2023-06-16 14:05 UTC, jafetsinke commented on bdi-frontend/src/appRouter.js
> +  { path: "/", component: LoginView },
path should be /login not /

2023-06-16 14:06 UTC, jafetsinke commented on bdi-frontend/src/appRouter.js
> +  { path: "/", component: LoginView },
i think lol

2023-06-19 09:11 UTC, jafetsinke approved these changes

2023-06-19 09:46 UTC, merged