Bdi 39 loginform - Eerste versie registratieformulier
BDI-HU/WeatherProject pull request #7
Opened 2023-03-27 21:31 UTC by timrebergen

Dit is de eerste versie van het registratieformulier. Momenteel nog zonder werkende back-end. @jafetsinke binnenkort even samen kijken? :)

2023-03-28 08:24 UTC, jafetsinke requested changes
Overall nice and clean code, suggested a few small changes

2023-03-28 08:24 UTC, jafetsinke commented on bdi-frontend/src/views/RegisterComponent.vue
> +        <v-card-title class="" style="color: #4FC6EC; font-weight: 700; font-size: 36px" align="center">
Try to prevent inline styles wherever possible, instead use for example `class="text-primary"`

2023-03-28 08:24 UTC, jafetsinke commented on bdi-frontend/src/views/RegisterComponent.vue
Overall clean and straightforward code, great use of Vuetify components.

2023-03-28 08:24 UTC, jafetsinke commented on bdi-frontend/Dockerfile
Dockerfile frontend should be combined with Dockerfile backend

2023-03-28 08:24 UTC, jafetsinke commented on bdi-frontend/src/views/RegisterComponent.vue
> +        <v-card-title class="" style="color: #4FC6EC; font-weight: 700; font-size: 36px" align="center">
As well as on line 71, there is a class for font weight as well built into Vuetify

2023-03-28 08:24 UTC, jafetsinke commented on bdi-frontend/src/views/RegisterComponent.vue
Show/hide password button is not working. Not sure about best practice, but imo the icon should have `cursor: pointer`

2023-03-28 08:24 UTC, jafetsinke commented on bdi-frontend/src/views/RegisterComponent.vue
Docent/Student buttons can be disabled as of now

2023-04-03 09:13 UTC, timrebergen commented on bdi-frontend/src/views/RegisterComponent.vue
Fixed

2023-04-03 09:18 UTC, jafetsinke approved these changes

2023-04-03 09:18 UTC, merged